WITH RECURSIVE OrderStep AS (
SELECT 
d.UNIT_NBR,
d.STEP_SEQ_ID,
p.STEP_PROG_NAME,
1 AS Execution_Order
from DEPENDENCY_RULES d
JOIN PROG_NAME p
ON d.UNIT_NBR = p.UNIT_NBR
AND d.STEP_SEQ_ID = p.STEP_SEQ_ID
WHERE d.STEP_DEP_ID = 0

UNION ALL

SELECT 
d.UNIT_NBR,
d.STEP_SEQ_ID,
p.STEP_PROG_NAME,
os.Execution_Order + 1
from DEPENDENCY_RULES d
JOIN PROG_NAME p
ON d.UNIT_NBR = p.UNIT_NBR
AND d.STEP_SEQ_ID = p.STEP_SEQ_ID
JOIN OrderStep os
ON d.STEP_DEP_ID = os.STEP_DEP_ID
AND d.UNIT_NBR = os.UNIT_NBR

)

SELECT 
UNIT_NBR,
STEP_SEQ_ID,
STEP_PROG_NAME,
Execution_Order
FROM OrderStep
ORDER BY UNIT_NBR,Execution_Order,STEP_SEQ_ID

